### ISSUE TITLE
[FEAT] <title>MONTEREY STYLE FOR WINDOWS PLEASE

### ISSUE THREAD

**Issue by kb12000** [AdamXweb/WhiteSurFirefoxThemeMacOS#105] opened 2023-10-09 15:37 UTC
### Describe the solution you'd like

PLEASE MAKE THIS VERSION IF POSSIBLE

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Yes!

**Comment by AdamXweb** [comment] 2023-10-11 05:59
Duplicate of #41 

From your request it doesn't seem like you're keen to implement this. Please raise a pull request if you would like a code review.

**Closed by AdamXweb** 2023-10-11 05:59 UTC
