### ISSUE TITLE
[BUG] Oversized titlebar buttons in latest Nightly build

### ISSUE THREAD

**Issue by gayfieri** [AdamXweb/WhiteSurFirefoxThemeMacOS#67] opened 2022-03-18 21:54 UTC
**Describe the bug**
the buttons are way too big, in the wrong order and don't hide the original windows buttons

**To Reproduce**
apply theme in firefox nightly

**Expected behavior**
buttons should be smaller and not cover back and forward page buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/94586008/159087990-95715de0-927e-46cf-81d5-276d74888646.png)

https://i.imgur.com/h7oghGi.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, build 19044
 - Firefox version Nightly 100.0a1
 - WhiteSur theme v1.4.1

**Comment by AdamXweb** [comment] 2022-03-20 12:07
Thanks for submitting the issue.
Will close as is a duplicate of #64

**Closed by AdamXweb** 2022-03-20 12:07 UTC
Labels: bug
