### ISSUE TITLE
[BUG] The theme malfunctioned on Firefox Nightly

### ISSUE THREAD

**Issue by thecursehunter** [AdamXweb/WhiteSurFirefoxThemeMacOS#66] opened 2022-03-13 04:22 UTC
**Describe the bug**
The 3 buttons at top left corner are messed up and the spaces between other stuffs are not correctly positioned

**To Reproduce**
1. Download Firefox Nightly with the default settings
2. Apply the theme
3. See error

**Expected behavior**
Make the theme work on Nightly I guess.

**Screenshots**
![Screenshot 2022-03-13 111106](https://user-images.githubusercontent.com/73272262/158044858-465d52d1-a49b-408b-a92e-f5a582bcd654.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
 - Firefox version 100.0a1
 - WhiteSur theme v1.4.1

**Comment by AdamXweb** [comment] 2022-03-13 12:33
Hi, thanks for reporting the bug. Will close as is a duplicate of #64

**Closed by AdamXweb** 2022-03-13 12:33 UTC
Labels: bug

**Comment by thecursehunter** [comment] 2022-03-13 13:11
> Hi, thanks for reporting the bug. Will close as is a duplicate of #64

Thanks
