### ISSUE TITLE
Windows Option to set tabs besides search bar instead of below. 

### ISSUE THREAD

**Issue by Sady-GuzmanT** [AdamXweb/WhiteSurFirefoxThemeMacOS#110] opened 2023-11-09 20:39 UTC
### Is your feature request related to a problem? If so, please describe.

In my linux laptop I installed the theme using the termial and there you can add flags to specify this feature. On my Windows PC I had to install the theme manually and this way I cant add flags on a terminal to specify the way I want the tabs to look.

Using Vince Liuice Repository Image to explain the two ways the tabs behave. On windows with manual instalation we only have ' Alt Style' Which takes more screen real state verticaly.

![monterey](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/83979853/4a452495-dcb7-45ed-b345-45292646df7b)

### Describe the solution you'd like

An option to toggle tabs being bellow/besides search bar, Like in linux.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by AdamXweb** [comment] 2024-12-01 11:14
duplicate of #41

**Closed by AdamXweb** 2024-12-01 11:14 UTC
