### ISSUE TITLE
Firefox Update Messed Theme

### ISSUE THREAD

**Issue by GameBoyzGB** [AdamXweb/WhiteSurFirefoxThemeMacOS#88] opened 2023-05-18 23:09 UTC
### Describe the problem

Firefox updated yesterday and now the theme is messed up. The tabs are now on top instead of below the address bar and the traffic buttons are reversed. Is there a quick fix? 

Thanks

### Version

Latest

### OS

Windows 11

### Firefox Version

113.0.1

### Install Options

none

### Colour Theme

No

### Additional info

![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/100013857/7a04dc73-c195-4344-a347-a7db801fe6d4)

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment] 2023-05-18 23:11
Hi,

Please download the latest release or the latest commit that both fix this issue

Duplicate of #86

**Closed** 2023-05-18 23:11 UTC

**Comment by GameBoyzGB** [comment] 2023-05-18 23:32
Thank you so much. BTW I'm not sure how to put the red traffic button to the left of the yellow. Right now, it's set as yellow, green and red.

**Comment by GameBoyzGB** [comment] 2023-05-18 23:45
Thank you it looks better now but the buttons are still swapped. I removed
the windows-swapclose out of the custom folder but the buttons still show
as yellow, green and red instead of red, yellow and green.  I don't know
how to use the scripting program and just overwrote the files in my profile.

Thanks again.
