### ISSUE TITLE
problem in closing minimizing and maximizing button[BUG]

### ISSUE THREAD

**Issue by ayaan07alam** [AdamXweb/WhiteSurFirefoxThemeMacOS#94] opened 2023-08-10 08:09 UTC
![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/77435615/aa6f44c7-a41f-4875-82d5-5345618d52f4)
how to solve this issue???

**Comment by AdamXweb** [comment] 2023-08-10 21:37
Hi @ayaan07alam, if you'd like assistance fixing this issue, please fill out the bug report with the info below


Describe the problem

Version

OS

Firefox Version

Install Options

Colour Theme

Additional info

**Comment by AdamXweb** [comment] 2023-09-02 08:17
Closing as no additional information was provided. Unable to reproduce the issue

**Closed by AdamXweb** 2023-09-02 08:17 UTC
