### ISSUE TITLE
Firefox 117 broke most features of this theme.

### ISSUE THREAD

**Issue by StickPal** [AdamXweb/WhiteSurFirefoxThemeMacOS#100] opened 2023-09-02 12:23 UTC
### Describe the problem

as the title suggests, this new version broke most things such as the **close, minimize, and restore** buttons, it also broke some fonts (i think??) and other things. this could be caused by something changed about sizes of images, but I haven't looked into it for now, that's in relation with the title bar icons ( as mentioned before ). I've also seen some similar issues with other themes, aparently If you were using appearance: `-moz-win-borderless-glass` somewhere in your code, it's broken now and it has to be commented out or removed. 

### Version

1.5.2

### OS

Windows 11

### Firefox Version

117

### Install Options

none

### Colour Theme

auto

### Additional info

![Screenshot 2023-08-31 145549](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/78269273/cb158797-ffaa-47ce-bf41-bb4483750c23)

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by Ayush-Kumar-web** [comment] 2023-09-04 07:03
did you find any solution yet? @StickPal

**Comment by StickPal** [comment] 2023-09-04 15:42
> did you find any solution yet? @StickPal

unfortunately no, I suppose your best solution at this moment would be to just downgrade to an earlier version like 115 etc, until Adam finds a better solution later on.

**Comment by AdamXweb** [comment] 2023-09-04 16:06
Hi @StickPal thanks for submitting the issue. This is a duplicate of #99 and #98, but there are a few good pickups like the spacing of buttons, font weight on tabs and a few other oddities with the tabsbar that have broken.
It looks like the bugs are limited to Windows, and i'll work on it as soon as I have access to a Windows VM again to test. In the meantime a pending pull request should fix the main issue of the window buttons.

Can you confirm if you've made any alterations for the tabs bar to be above the URL bar?

**Comment by StickPal** [comment] 2023-09-04 16:26
> Hi @StickPal thanks for submitting the issue. This is a duplicate of #99 and #98, but there are a few good pickups like the spacing of buttons, font weight on tabs and a few other oddities with the tabsbar that have broken. It looks like the bugs are limited to Windows, and i'll work on it as soon as I have access to a Windows VM again to test. In the meantime a pending pull request should fix the main issue of the window buttons.
> 
> Can you confirm if you've made any alterations for the tabs bar to be above the URL bar?

Hey @AdamXweb thanks for coming back this quickly! I can confirm that I have not changed anything in the files to make the tabs bar go above the URL bar. I actually didn't notice it until this message. I must've paid more attention to the buttons, etc.

**Comment by AdamXweb** [comment] 2023-09-05 05:43
I've released v1.5.3, please test to ensure it works on your machine.
Can confirm is working on Windows 11 v117
<img width="923" alt="Screenshot 2023-09-05 at 3 43 31 pm" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/bcf5c203-c1f5-49e3-aad2-0214f258259f">

**Comment by StickPal** [comment] 2023-09-05 19:31
> I've released v1.5.3, please test to ensure it works on your machine. Can confirm is working on Windows 11 v117 <img alt="Screenshot 2023-09-05 at 3 43 31 pm" width="923" src="https://user-images.githubusercontent.com/6800453/265596655-bcf5c203-c1f5-49e3-aad2-0214f258259f.png">
I can confirm that the issue has been fixed, and it's now working perfectly. Thank you so much!
![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/78269273/8366b6f1-dbff-4621-b38a-2edc4ca0f01a)

**Comment by StickPal** [comment] 2023-09-05 19:33
All though, I can now see a tiny issue with how the window border is set up, this could easily be a windows thing and nothing to do with the theme but I'am seeing a tiny change in how the icons are positioned, but honestly, the problem isn't that big and really it shouldn't be changed, But thanks alot! 
![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/78269273/7bd14c7f-58b7-4f99-a792-7714a4289106)

**Comment by Ayush-Kumar-web** [comment] 2023-09-06 05:27
Thanks @AdamXweb @StickPal for solving this issue.

**Closed** 2024-10-27 01:03 UTC
Labels: 🐛 bug, 🪟 Windows
