### ISSUE TITLE
[FEAT] Any chance of Monterey Safari support?

### ISSUE THREAD

**Issue by jsuri5356** [AdamXweb/WhiteSurFirefoxThemeMacOS#54] opened 2021-12-17 02:16 UTC
**Describe the solution you'd like**
Just was wondering if you were down to create a Monterey Safari version of this

**Describe alternatives you've considered**
N/A

**Additional context**
Just wanted to say awesome work on this project!

**Comment by AdamXweb** [comment] 2022-01-19 07:41
Duplicate of #41

**Closed by AdamXweb** 2022-01-19 07:41 UTC
Labels: enhancement
