### ISSUE TITLE
[FEAT] <title> Safari 15 style one lline theme

### ISSUE THREAD

**Issue by kb12000** [AdamXweb/WhiteSurFirefoxThemeMacOS#106] opened 2023-10-20 17:50 UTC
### Is your feature request related to a problem? If so, please describe.

can you make this theme  like monterey style please for windows ??

![Screenshot 2023-10-20 230612](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/98652005/df60a471-f16a-4545-a26b-11e4aba1a152)

### Describe the solution you'd like

oneline styled safari theme would be better

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Maybe

**Comment by AdamXweb** [comment] 2023-10-21 23:37
Duplicate of #41

**Closed by AdamXweb** 2023-10-21 23:37 UTC
